# -*- coding: utf-8 -*-
"""Assignment1ques1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fmlJm7A8h4YicgDUhOVMECq8CuFbx3RD
"""

import pandas as pd
import matplotlib.pyplot as plt
import math
data= pd.read_csv('daily_data.csv')
mean =0
st=0
dailyreturns=[0]
sharpe_ratio=[0]
data['temp']=(data['close']-data['open'])

for i in range(0,len(data.close)-1):
     mean=(mean*(i)+(data.close[i+1]-data.close[i])/data.close[i])/(i+1)
     st=((mean-(data.close[i+1]-data.close[i])/data.close[i])**2/(i+1))**0.5
     dailyreturns.append((data.close[i + 1] - data.close[i]) / data.close[i])
     sharpe_ratio.append((dailyreturns[i + 1] - 4.23)/st)

data.insert(2, 'dailyreturns', dailyreturns)
data.insert(3, 'sharpe_ratio', sharpe_ratio)
data['open/close']=data['open']/data['close']
data['low/high']=data['low']/data['high']
data['sorted_categories']=pd.cut(data['low/high'],bins=[0,0.2,0.4,0.6,0.8,1],labels=['[0 to 0.2]','[0.2 to 0.4]','[0.4 to 0.6]','[0.6 to 0.8]','[0.8 to 1]'])
print(data)
plot1=plt.plot(data['datetime'],data['temp'])
plt.xlabel('datetime')
plt.ylabel('temp')
plt.show()


plt.hist(data['low/high'],bins=[0,0.2,0.4,0.6,0.8,1])
plt.xlabel('low/high')
plt.ylabel('number of days')
plt.show()