# -*- coding: utf-8 -*-
"""Assignment1Ques2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WtUrfG03NTxPOMAkqZr37EPQb6BJQgFk
"""

import pandas as pd

def trade():
    data = pd.read_csv('daily_data.csv')
    stoploss = float(input("Enter the stop loss : "))
    takeprofit = float(input("Enter the take profit : "))

    buy = [data.datetime[0]]
    sell = [0]
    c = 1
    closing = data['close'].tolist()
    date=data['datetime'].tolist()

    for i in range(1, len(closing)-1):
        if (closing[i] < (closing[c] - (closing[c] * stoploss)) or closing[i] > (closing[c] + (closing[c] * takeprofit))):
            c = i
            sell.append(date[c])
            buy.append(date[c+1])

    print("Buy ",buy)
    print("Sell ",sell)

trade()